remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: air
locale: en-US
title: sheldonhull.com
title_separator: '-'
name: Sheldon Hull
description: random thoughts and ramblings
url: 'https://www.sheldonhull.com'
baseurl: ''
repository: sheldonhull/sheldonhull.github.io
teaser: /assets/img/sheldon_400x400.jpg
breadcrumbs: false
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: sheldonhull
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: "https://www.feedio.co/@sheldon_hull?came_from=homepagefeedbutton"
search: true
#search_full_content: true  #only needed for lur
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: sheldon_hull
facebook:
  username: null
  app_id: null
  publisher: null
og_image: /assets/img/sheldon_400x400.jpg
social:
  type: null
  name: null
  links: null
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-40198001-3
author:
  name: Sheldon Hull
  avatar: /assets/img/sheldon_400x400.jpg
  bio: Resident automator of spline reticulation
  location: 'Houston, TX'
  email: null
  uri: null
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: sheldonhull
  gitlab: null
  google_plus: null
  keybase: null
  instagram: sheldonhull
  lastfm: null
  linkedin: 'https://www.linkedin.com/in/sheldonhull/'
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: sheldon_hull
  vine: null
  weibo: null
  xing: null
  youtube: 'https://www.youtube.com/channel/UCp7hPP_Rb6_wK5eghTBYKJg'
include:
  - .htaccess
  - _pages
  - _portfolio
  - _redirects
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
  - .ps1
  - .sh
  - .bat
  - _oldsitemap
  - /util
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+

incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: sql
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true




sass:
  sass_dir: _sass
  style: compressed

permalink: '/:categories/:title/'
paginate: 8
paginate_path: '/page:num/'


timezone: America/Chicago
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-mermaid
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-algolia
  - premonition
  #- jekyll-paginate-v2  
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
#https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - tags
     - categories
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      toc: true
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      permalink: /blog/:title
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ''
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: docs
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

search_provider: algolia
algolia:
  application_id         : 04HSGXXQD5
  index_name             : sheldonhull.com
  search_only_api_key    : a7ec2763a5d966a5b9f8d70b254bfb68
  powered_by             : true
  files_to_exclude       :
    - archive/*.html
    - categories/*.html
    - collection-archive/*.html
    - date-archive/*.html
    - page-archive/*.html
    - pages/*.md
    - pages/*.html
    - util/*
  settings:
    highlightPreTag: '<em class="custom_highlight">'
    highlightPostTag: '</em>'

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global

# ############################################################
# # Site configuration for the Jekyll 3 Pagination Gem
# # The values here represent the defaults if nothing is set
# pagination:
  
#   # Site-wide kill switch, disabled here it doesn't run at all 
#   enabled: true

#   # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
#   debug: false

#   # The default document collection to paginate if nothing is specified ('posts' is default)
#   collection: 'posts'

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
#   per_page: 10

#   # The permalink structure for the paginated pages (this can be any level deep)
#   permalink: '/page/:num/' # Pages are index.html inside this folder (default)
#   #permalink: '/page/:num.html' # Pages are simple html files 
#   #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

#   # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
#   title: ':title - page :num'

#   # Limit how many pagenated pages to create (default: 0, means all)
#   limit: 0
  
#   # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
#   sort_field: 'date'

#   # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
#   sort_reverse: true

#   # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
#   category: 'posts'

#   # Optional, the default tag to use, omit to disable
#   tag: ''

#   # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
#   # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
#   locale: 'en_US' 

#  # Optional,omit or set both before and after to zero to disable. 
#  # Controls how the pagination trail for the paginated pages look like. 
#   trail: 
#     before: 2
#     after: 2

#   # Optional, the default file extension for generated pages (e.g html, json, xml).
#   # Internally this is set to html by default
#   extension: html

#   # Optional, the default name of the index file for generated pages (e.g. 'index.html')
#   # Without file extension
#   indexpage: 'index'

# ############################################################

# # Plugin: Auto Pages (jekyll-paginate-v2)
# autopages:
#   enabled      : true
#   categories:
#     enabled    : true
#     slugify:
#       mode: nil
#       cased: true
#     layouts:
#       - "autopage_categories.html"
#     title      : ':category“' # :category is replaced by the category name
#     permalink  : "/category/:category"
#   collections:
#     enabled    : false
#   tags:
#     enabled    : true
#     slugify:
#       mode: nil
#       cased: true
#     layouts:
#       - "autopage_tags.html"
#     title      : ':tag“' # :tag is replaced by the tag name
#     permalink  : "/tag/:tag"