remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: air
locale: en-US
title: sheldonhull.com
title_separator: '-'
name: Sheldon Hull
description: random thoughts and ramblings
url: 'https://www.sheldonhull.com'
baseurl: ''
repository: sheldonhull/sheldonhull.github.io
teaser: null
breadcrumbs: true
words_per_minute: 200
comments:
  provider: Disqus
  disqus:
    shortname: sheldonhull
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: "https://www.feedio.co/@sheldon_hull?came_from=homepagefeedbutton"
search: true
#search_full_content: true  #only needed for lur
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: sheldon_hull
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-40198001-3
author:
  name: Sheldon Hull
  avatar: /assets/img/sheldon_400x400.jpg
  bio: Resident automator of spline reticulation
  location: 'Houston, TX'
  email: null
  uri: null
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: sheldonhull
  gitlab: null
  google_plus: null
  keybase: null
  instagram: sheldonhull
  lastfm: null
  linkedin: 'https://www.linkedin.com/in/sheldonhull/'
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: sheldon_hull
  vine: null
  weibo: null
  xing: null
  youtube: 'https://www.youtube.com/channel/UCp7hPP_Rb6_wK5eghTBYKJg'
include:
  - .htaccess
  - _pages
  - _portfolio
  - _redirects
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
  - .ps1
  - .sh
  - .bat
  - _oldsitemap
  - /util
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+

incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: sql
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true




sass:
  sass_dir: _sass
  style: compressed

permalink: '/:categories/:title/'
paginate: 8
paginate_path: '/page:num/'
timezone: America/Chicago
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-mermaid
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-algolia
  - premonition

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
#https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - tags
     - categories
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      permalink: /blog/:title
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ''
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: docs
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

search_provider: algolia
algolia:
  application_id         : 04HSGXXQD5
  index_name             : sheldonhull.com
  search_only_api_key    : a7ec2763a5d966a5b9f8d70b254bfb68
  powered_by             : true
  files_to_exclude       :
    - archive/*.html
    - categories/*.html
    - collection-archive/*.html
    - date-archive/*.html
    - page-archive/*.html
    - pages/*.md
    - pages/*.html
    - util/*
  settings:
    highlightPreTag: '<em class="custom_highlight">'
    highlightPostTag: '</em>'

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
