url: http://localhost:4000 # the base hostname & protocol
host: localhost
port: 4000
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-mermaid
  - jekyll-archives
  - jekyll-remote-theme
#  - jekyll-algolia
  - premonition
  - jekyll-include-cache
  - jekyll-picture-tag
future: true
#plugins_dir: .\_plugins_dev
analytics:
  provider: #google-gtag
  google:
    tracking_id:
search_provider: lunr