minimal_mistakes_skin: contrast
locale: en-US
title: sheldonhull.com
title_separator: '-'
name: Sheldon Hull
description: random thoughts and ramblings by yours truly
url: 'https://sheldonhull.github.io'
baseurl: ''
repository: sheldonhull/sheldonhull.github.io
teaser: null
breadcrumbs: true
words_per_minute: 200
comments:
  provider: null
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
search: true
search_full_content: true
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: false
  google:
    tracking_id: null
author:
  name: Sheldon Hull
  avatar: null
  bio: Resident automator of spline reticulation
  location: 'Houston, TX'
  email: null
  uri: null
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: sheldonhull
  gitlab: null
  google_plus: null
  keybase: null
  instagram: sheldonhull
  lastfm: null
  linkedin: 'https://www.linkedin.com/in/sheldonhull/'
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: sheldon_hull
  vine: null
  weibo: null
  xing: null
  youtube: 'https://www.youtube.com/channel/UCp7hPP_Rb6_wK5eghTBYKJg'
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: America/Chicago
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: null
      share: true
      related: true
