remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark
locale: en-US
title: sheldonhull.com
title_separator: '-'
name: Sheldon Hull
description: random thoughts and ramblings
url: 'https://www.sheldonhull.com'
baseurl: ''
repository: sheldonhull/sheldonhull.github.io
teaser: /assets/img/sheldon_200x200.jpg
breadcrumbs: true
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: sheldonhull
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: "https://www.feedio.co/@sheldon_hull?came_from=homepagefeedbutton"
search: true
#search_full_content: true  #only needed for lur
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: sheldon_hull
facebook:
  username: null
  app_id: null
  publisher: null
og_image: /assets/img/sheldon_200x200.jpg
social:
  type: null
  name: null
  links: null
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-40198001-3
author:
  name: Sheldon Hull
  avatar: /assets/img/sheldon_120x120.jpg
  bio: Resident automator of spline reticulation
  location: 'Houston, TX'
  email: null
  uri: null
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: sheldonhull
  gitlab: null
  google_plus: null
  keybase: null
  instagram: null
  lastfm: null
  linkedin: 'https://www.linkedin.com/in/sheldonhull/'
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: sheldon_hull
  vine: null
  weibo: null
  xing: null
  youtube: 'https://www.youtube.com/channel/UCp7hPP_Rb6_wK5eghTBYKJg'
include:
  - .htaccess
  - _pages
  - _portfolio
  - _redirects
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
  - .ps1
  - .sh
  - .bat
  - _oldsitemap
  - /util
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"


head_scripts:
  - https://cdn.jsdelivr.net/npm/netlify-cms@^2.0.0/dist/netlify-cms.js
  - https://identity.netlify.com/v1/netlify-identity-widget.js
  #- https://cdnjs.cloudflare.com/ajax/libs/fluidbox/2.0.5/css/fluidbox.min.css

# Note: If you assign footer_scripts the theme's /assets/js/main.min.js file will be deactivated.
# This script includes jQuery and various other plugins that you'll need to find replacements for and include separately.
# footer_scripts:
#   - https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.min.js
#   - https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js
#   - https://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js
#   - https://cdnjs.cloudflare.com/ajax/libs/fluidbox/2.0.5/js/jquery.fluidbox.min.js

incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: sql
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

future: false
permalink: '/:categories/:title/'
paginate: 8
paginate_path: '/page:num/'
timezone: America/Chicago
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-mermaid
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-algolia
  - premonition
  - jekyll-include-cache
  # - jekyll-webp
  - jekyll-picture-tag

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - premonition
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
#https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - tags
     - categories
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      permalink: /blog/:title
      classes: wide
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ''
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: docs
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

search_provider: algolia
algolia:
  application_id         : 04HSGXXQD5
  index_name             : sheldonhull.com
  search_only_api_key    : a7ec2763a5d966a5b9f8d70b254bfb68
  powered_by             : true
  files_to_exclude       :
    - archive/*.html
    - categories/*.html
    - collection-archive/*.html
    - date-archive/*.html
    - page-archive/*.html
    - pages/*.md
    - pages/*.html
    - util/*
  settings:
    highlightPreTag: '<em class="custom_highlight">'
    highlightPostTag: '</em>'

# Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
# span, block element options fall back to global
prose:
  rooturl: '_posts'
  siteurl: 'https://www.sheldonhull.com'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: '/assets/img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "date"
          value: "CURRENT_DATETIME"
      - name: "excerpt"
        field:
          element: "text"
          label: "excerpt"
          value: ""
      # - name: "layout"
      #   field:
      #     element: "hidden"
          # value: "blog"
      # - name: "tags"
      #   field:
      #     element: "text"
      #     label: "Add Tags"
      #     value: "[\"tech\"]"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "sql-server"
              value: "sql-server"
            - name: "tech"
              value: "tech"
            - name: "ramblings"
              value: "ramblings"
      - name: "last_modified_at"
        field:
          element: "text"
          label: "last_modified_at"
          value: "CURRENT_DATETIME"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          help: "To ensure this can save drafts with no issues, each new post is set to false on publish to prevent it from being in feed. Have to set manually to true to allow post to generate in feed"
          value: false
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""


############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: false

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will not be checked
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/img"]

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".gif",".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []
############################################################