---
new_page_extension: md
auto_deploy: false
admin_path:

# forestry config front matter config
front_matter_path: '/front_matter/templates'

# forestry config File naming
use_front_matter_path: true
file_template: ":year:-:month:-:day:-:filename:"

#  forestry config for uploading images and files
upload_dir: '/assets/img'
public_path: '/assets/img'

#sections of pages
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-portfolio
  label: Portfolio
  create: all
- type: directory
  path: ''
  label: pages
  create: all
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md




# authorizing image path for writing
frontmatter_file_url_template: "{{ site.url }}{{ site.baseurl }}/assets/img"
body_file_url_template: "{{ site.url }}{{ site.baseurl }}/assets/img"


# event webhook
#webhook_url: https://api.netlify.com/build_hooks/5ab28b487b6ee83f6119e06b