---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: https://api.netlify.com/build_hooks/5ab28b487b6ee83f6119e06b
sections:
- type: jekyll-posts
  label: post
  create: all
  templates:
  - post
- type: directory
  path: _portfolio
  label: portfolio
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/img
public_path: "{{ site.url }}{{ site.baseurl }}/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:-:day:-:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
    -V
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=dev
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
